#!/usr/bin/env python3
"""
scrape_player_stats.py — Daily NBA/NHL player season-stats snapshot.
(WNBA removed 2026-09-08 -- retired from the engine entirely, and its
render/prop-generation functions are gone from docs/app.html, so nothing
there has requested a "wnba" key from this script's output since.)

Fixes a real, pre-existing bug in docs/app.html: _fetchNBAPlayerStats() /
_fetchNHLPlayerStats() (and the since-removed _fetchWNBAPlayerStats())
all parse site.api.espn.com/.../statistics?limit=300 assuming a flat
top-level `athletes[]` array. That key has never existed on this
endpoint -- the real shape is `stats.categories[].leaders[]` (per-category
leaderboards, ~50 players each, each leader carrying a FULL nested
per-game stat line at leader.statistics.splits.categories).
`(d.athletes||[]).forEach(...)` has therefore always silently produced an
empty object, in every context (headless or a real browser) -- confirmed
by fetching the live endpoint directly and inspecting its actual
top-level keys (['timestamp','status','season','league','stats'], no
'athletes'). This has meant zero player props generated by
_generateNBAProps/_generateNHLPropsLive since those functions were
written, not just since the headless auto-lock driver
(auto_lock_settle.py) launched on 2026-08-11 -- that script's own logs
just happened to be the first place anyone could see "0 prop legs"
spelled out explicitly every single run.

This script fetches the same endpoint server-side (unblocked `requests`
path, same principle as scrape_soccer_standings.py) using the REAL
response shape, and writes docs/player_stats.json so the client can fall
back to it. docs/app.html's three fetch functions are fixed to match
this same corrected parsing directly (this script isn't strictly a CORS
workaround the way scrape_soccer_standings.py is -- it exists mainly so
the headless auto-lock driver, which can't rely on live ESPN fetches
succeeding in an automation context at all, still has real same-day data
to build props from).

Standalone script, same convention as scrape_opta_stats.py /
scrape_soccer_standings.py (no import dependency on
clairvoyance_update.py).

Usage:
  python3 scripts/scrape_player_stats.py            # scrape + write, no push
  python3 scripts/scrape_player_stats.py --push     # scrape + write + commit + push
"""
from __future__ import annotations
import argparse, json, subprocess, sys, time
from datetime import datetime, timezone
from pathlib import Path

import requests

ROOT = Path(__file__).parent.parent
OUT = ROOT / "docs" / "player_stats.json"

STATS_URLS = {
    "nba": "https://site.api.espn.com/apis/site/v2/sports/basketball/nba/statistics?limit=300",
    "nhl": "https://site.api.espn.com/apis/site/v2/sports/hockey/nhl/statistics?limit=300",
}

# Which leader categories to union to build the player pool for each sport --
# a player only needs to crack ONE of these top-~50 leaderboards to be
# included, so between 2-3 categories this covers essentially every real
# rotation player, not just outright league leaders.
ANCHOR_CATEGORIES = {
    "nba": ["pointsPerGame", "reboundsPerGame", "assistsPerGame"],
    "nhl": ["points", "goals", "assists"],
}


def log(msg: str) -> None:
    ts = datetime.now(timezone.utc).strftime("%H:%M:%S")
    print(f"[{ts}] {msg}", flush=True)


def _flatten_leader_stats(leader: dict) -> dict:
    """leader.statistics.splits.categories is a nested
    [{name:'offensive', stats:[{name:'avgPoints', value:18.5}, ...]}, ...]
    structure -- flatten to {statName: value} across every sub-category,
    same shape _raw_categories-style helpers elsewhere in this pipeline use."""
    flat: dict[str, float] = {}
    splits = ((leader.get("statistics") or {}).get("splits") or {})
    for cat in splits.get("categories") or []:
        for s in cat.get("stats") or []:
            name = s.get("name")
            if not name:
                continue
            try:
                flat[name] = float(s.get("value"))
            except (TypeError, ValueError):
                pass
    return flat


def _collect_players(categories: list[dict], anchors: list[str]) -> dict[str, dict]:
    """Union the leaders of `anchors` categories, deduped by athlete id,
    keeping each unique athlete's leader entry (any one of them -- the
    full per-game stat line lives on leader.statistics regardless of
    which category found them)."""
    by_id: dict[str, dict] = {}
    cat_by_name = {c.get("name"): c for c in categories}
    for name in anchors:
        cat = cat_by_name.get(name)
        if not cat:
            continue
        for leader in cat.get("leaders") or []:
            athlete = leader.get("athlete") or {}
            aid = athlete.get("id")
            if not aid or aid in by_id:
                continue
            by_id[aid] = leader
    return by_id


def fetch_basketball(url: str) -> dict:
    r = requests.get(url, timeout=15)
    r.raise_for_status()
    data = r.json()
    categories = ((data.get("stats") or {}).get("categories")) or []
    players = _collect_players(categories, ANCHOR_CATEGORIES["nba"])

    by_name: dict[str, dict] = {}
    for leader in players.values():
        athlete = leader.get("athlete") or {}
        name = athlete.get("displayName")
        if not name:
            continue
        team = (leader.get("team") or {}).get("abbreviation") or ""
        flat = _flatten_leader_stats(leader)
        gp = max(1, flat.get("gamesPlayed") or 1)
        ppg = flat.get("avgPoints") or 0.0
        by_name[name.lower()] = {
            "name": name, "team": team, "gp": round(gp),
            "ppg": round(ppg, 1),
            "rpg": round(flat.get("avgRebounds") or 0.0, 1),
            "apg": round(flat.get("avgAssists") or 0.0, 1),
            "tpg": round(flat.get("avgThreePointFieldGoalsMade") or 0.0, 1),
            "bpg": round(flat.get("avgBlocks") or 0.0, 1),
            "spg": round(flat.get("avgSteals") or 0.0, 1),
            "sigma": round((ppg ** 0.5) * 1.2, 2) if ppg else 5.0,
        }
    return by_name


def fetch_nhl(url: str) -> dict:
    r = requests.get(url, timeout=15)
    r.raise_for_status()
    data = r.json()
    categories = ((data.get("stats") or {}).get("categories")) or []
    players = _collect_players(categories, ANCHOR_CATEGORIES["nhl"])

    by_name: dict[str, dict] = {}
    for leader in players.values():
        athlete = leader.get("athlete") or {}
        name = athlete.get("displayName")
        if not name:
            continue
        team = (leader.get("team") or {}).get("abbreviation") or ""
        flat = _flatten_leader_stats(leader)
        gp = max(1, flat.get("games") or 1)
        assists = flat.get("assists") or 0.0
        by_name[name.lower()] = {
            "name": name, "team": team, "gp": round(gp),
            "gpg": round((flat.get("avgGoals") or 0.0), 2),
            "apg": round(assists / gp, 2),
            "ppg": round(flat.get("pointsPerGame") or 0.0, 2),
            "shpg": round(flat.get("avgShots") or 0.0, 1),
        }
    return by_name


FETCHERS = {"nba": fetch_basketball, "nhl": fetch_nhl}


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--push", action="store_true")
    args = ap.parse_args()

    result: dict[str, dict] = {}
    for key, url in STATS_URLS.items():
        try:
            by_name = FETCHERS[key](url)
            result[key] = by_name
            log(f"{key.upper()}: {len(by_name)} players")
        except Exception as exc:
            log(f"{key.upper()}: FAILED {exc}")
            result[key] = {}
        time.sleep(0.5)

    if not any(result.values()):
        log("no data for any sport -- not writing (expected during NBA/NHL off-season)")
        sys.exit(0)

    result["generatedAt"] = datetime.now(timezone.utc).isoformat()
    OUT.write_text(json.dumps(result, indent=2))
    log(f"wrote {OUT}")

    if args.push:
        subprocess.run(["git", "add", "docs/player_stats.json"], cwd=ROOT, check=True)
        commit = subprocess.run(
            ["git", "commit", "-m", "chore: refresh player stats snapshot"],
            cwd=ROOT, capture_output=True, text=True,
        )
        if commit.returncode != 0:
            log("nothing to commit")
            return
        for attempt in range(5):
            subprocess.run(["git", "pull", "--rebase", "origin", "main"], cwd=ROOT, capture_output=True)
            push = subprocess.run(["git", "push", "origin", "main"], cwd=ROOT, capture_output=True, text=True)
            if push.returncode == 0:
                log("pushed")
                return
            log(f"push attempt {attempt+1}/5 failed, retrying: {push.stderr.strip()[:160]}")
            time.sleep(3 + attempt * 2)
        raise RuntimeError("git push failed after 5 retries")


if __name__ == "__main__":
    main()
